backend:
  name: github
  repo: toygarcaparoglu/redpill
  branch: main
  auth_scope: repo
  base_url: https://debuggingme.netlify.app/.netlify/functions
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Başlık"
        name: "title"
        widget: "string"
      - label: "Tarih"
        name: "date"
        widget: "datetime"
      - label: "İçerik"
        name: "body"
        widget: "markdown"
